/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.sohu.bp.elite.model;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class TAnswerIdListResult implements org.apache.thrift.TBase<TAnswerIdListResult, TAnswerIdListResult._Fields>, java.io.Serializable, Cloneable {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("TAnswerIdListResult");

  private static final org.apache.thrift.protocol.TField ANSWER_IDS_FIELD_DESC = new org.apache.thrift.protocol.TField("answerIds", org.apache.thrift.protocol.TType.LIST, (short)1);
  private static final org.apache.thrift.protocol.TField TOTAL_FIELD_DESC = new org.apache.thrift.protocol.TField("total", org.apache.thrift.protocol.TType.I64, (short)2);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new TAnswerIdListResultStandardSchemeFactory());
    schemes.put(TupleScheme.class, new TAnswerIdListResultTupleSchemeFactory());
  }

  public List<Long> answerIds; // required
  public long total; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    ANSWER_IDS((short)1, "answerIds"),
    TOTAL((short)2, "total");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // ANSWER_IDS
          return ANSWER_IDS;
        case 2: // TOTAL
          return TOTAL;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __TOTAL_ISSET_ID = 0;
  private byte __isset_bitfield = 0;
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.ANSWER_IDS, new org.apache.thrift.meta_data.FieldMetaData("answerIds", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64))));
    tmpMap.put(_Fields.TOTAL, new org.apache.thrift.meta_data.FieldMetaData("total", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(TAnswerIdListResult.class, metaDataMap);
  }

  public TAnswerIdListResult() {
    this.total = 0L;

  }

  public TAnswerIdListResult(
    List<Long> answerIds,
    long total)
  {
    this();
    this.answerIds = answerIds;
    this.total = total;
    setTotalIsSet(true);
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public TAnswerIdListResult(TAnswerIdListResult other) {
    __isset_bitfield = other.__isset_bitfield;
    if (other.isSetAnswerIds()) {
      List<Long> __this__answerIds = new ArrayList<Long>();
      for (Long other_element : other.answerIds) {
        __this__answerIds.add(other_element);
      }
      this.answerIds = __this__answerIds;
    }
    this.total = other.total;
  }

  public TAnswerIdListResult deepCopy() {
    return new TAnswerIdListResult(this);
  }

  @Override
  public void clear() {
    this.answerIds = null;
    this.total = 0L;

  }

  public int getAnswerIdsSize() {
    return (this.answerIds == null) ? 0 : this.answerIds.size();
  }

  public java.util.Iterator<Long> getAnswerIdsIterator() {
    return (this.answerIds == null) ? null : this.answerIds.iterator();
  }

  public void addToAnswerIds(long elem) {
    if (this.answerIds == null) {
      this.answerIds = new ArrayList<Long>();
    }
    this.answerIds.add(elem);
  }

  public List<Long> getAnswerIds() {
    return this.answerIds;
  }

  public TAnswerIdListResult setAnswerIds(List<Long> answerIds) {
    this.answerIds = answerIds;
    return this;
  }

  public void unsetAnswerIds() {
    this.answerIds = null;
  }

  /** Returns true if field answerIds is set (has been assigned a value) and false otherwise */
  public boolean isSetAnswerIds() {
    return this.answerIds != null;
  }

  public void setAnswerIdsIsSet(boolean value) {
    if (!value) {
      this.answerIds = null;
    }
  }

  public long getTotal() {
    return this.total;
  }

  public TAnswerIdListResult setTotal(long total) {
    this.total = total;
    setTotalIsSet(true);
    return this;
  }

  public void unsetTotal() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __TOTAL_ISSET_ID);
  }

  /** Returns true if field total is set (has been assigned a value) and false otherwise */
  public boolean isSetTotal() {
    return EncodingUtils.testBit(__isset_bitfield, __TOTAL_ISSET_ID);
  }

  public void setTotalIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __TOTAL_ISSET_ID, value);
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case ANSWER_IDS:
      if (value == null) {
        unsetAnswerIds();
      } else {
        setAnswerIds((List<Long>)value);
      }
      break;

    case TOTAL:
      if (value == null) {
        unsetTotal();
      } else {
        setTotal((Long)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case ANSWER_IDS:
      return getAnswerIds();

    case TOTAL:
      return Long.valueOf(getTotal());

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case ANSWER_IDS:
      return isSetAnswerIds();
    case TOTAL:
      return isSetTotal();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof TAnswerIdListResult)
      return this.equals((TAnswerIdListResult)that);
    return false;
  }

  public boolean equals(TAnswerIdListResult that) {
    if (that == null)
      return false;

    boolean this_present_answerIds = true && this.isSetAnswerIds();
    boolean that_present_answerIds = true && that.isSetAnswerIds();
    if (this_present_answerIds || that_present_answerIds) {
      if (!(this_present_answerIds && that_present_answerIds))
        return false;
      if (!this.answerIds.equals(that.answerIds))
        return false;
    }

    boolean this_present_total = true;
    boolean that_present_total = true;
    if (this_present_total || that_present_total) {
      if (!(this_present_total && that_present_total))
        return false;
      if (this.total != that.total)
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  public int compareTo(TAnswerIdListResult other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;
    TAnswerIdListResult typedOther = (TAnswerIdListResult)other;

    lastComparison = Boolean.valueOf(isSetAnswerIds()).compareTo(typedOther.isSetAnswerIds());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetAnswerIds()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.answerIds, typedOther.answerIds);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetTotal()).compareTo(typedOther.isSetTotal());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetTotal()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.total, typedOther.total);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("TAnswerIdListResult(");
    boolean first = true;

    sb.append("answerIds:");
    if (this.answerIds == null) {
      sb.append("null");
    } else {
      sb.append(this.answerIds);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("total:");
    sb.append(this.total);
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class TAnswerIdListResultStandardSchemeFactory implements SchemeFactory {
    public TAnswerIdListResultStandardScheme getScheme() {
      return new TAnswerIdListResultStandardScheme();
    }
  }

  private static class TAnswerIdListResultStandardScheme extends StandardScheme<TAnswerIdListResult> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, TAnswerIdListResult struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // ANSWER_IDS
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list50 = iprot.readListBegin();
                struct.answerIds = new ArrayList<Long>(_list50.size);
                for (int _i51 = 0; _i51 < _list50.size; ++_i51)
                {
                  long _elem52; // required
                  _elem52 = iprot.readI64();
                  struct.answerIds.add(_elem52);
                }
                iprot.readListEnd();
              }
              struct.setAnswerIdsIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // TOTAL
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.total = iprot.readI64();
              struct.setTotalIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, TAnswerIdListResult struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.answerIds != null) {
        oprot.writeFieldBegin(ANSWER_IDS_FIELD_DESC);
        {
          oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.I64, struct.answerIds.size()));
          for (long _iter53 : struct.answerIds)
          {
            oprot.writeI64(_iter53);
          }
          oprot.writeListEnd();
        }
        oprot.writeFieldEnd();
      }
      oprot.writeFieldBegin(TOTAL_FIELD_DESC);
      oprot.writeI64(struct.total);
      oprot.writeFieldEnd();
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class TAnswerIdListResultTupleSchemeFactory implements SchemeFactory {
    public TAnswerIdListResultTupleScheme getScheme() {
      return new TAnswerIdListResultTupleScheme();
    }
  }

  private static class TAnswerIdListResultTupleScheme extends TupleScheme<TAnswerIdListResult> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, TAnswerIdListResult struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetAnswerIds()) {
        optionals.set(0);
      }
      if (struct.isSetTotal()) {
        optionals.set(1);
      }
      oprot.writeBitSet(optionals, 2);
      if (struct.isSetAnswerIds()) {
        {
          oprot.writeI32(struct.answerIds.size());
          for (long _iter54 : struct.answerIds)
          {
            oprot.writeI64(_iter54);
          }
        }
      }
      if (struct.isSetTotal()) {
        oprot.writeI64(struct.total);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, TAnswerIdListResult struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(2);
      if (incoming.get(0)) {
        {
          org.apache.thrift.protocol.TList _list55 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.I64, iprot.readI32());
          struct.answerIds = new ArrayList<Long>(_list55.size);
          for (int _i56 = 0; _i56 < _list55.size; ++_i56)
          {
            long _elem57; // required
            _elem57 = iprot.readI64();
            struct.answerIds.add(_elem57);
          }
        }
        struct.setAnswerIdsIsSet(true);
      }
      if (incoming.get(1)) {
        struct.total = iprot.readI64();
        struct.setTotalIsSet(true);
      }
    }
  }

}

