/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.sohu.bp.elite.model;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum TEliteSourceType implements org.apache.thrift.TEnum {
  WRITE_PC(1),
  WRITE_MOBILE(2),
  WRITE_APP(3),
  WRITE_WX(4),
  CRAWL(10);

  private final int value;

  private TEliteSourceType(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static TEliteSourceType findByValue(int value) { 
    switch (value) {
      case 1:
        return WRITE_PC;
      case 2:
        return WRITE_MOBILE;
      case 3:
        return WRITE_APP;
      case 4:
        return WRITE_WX;
      case 10:
        return CRAWL;
      default:
        return null;
    }
  }
}
