/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.sohu.bp.elite.model;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum TEliteMessageFrequenceType implements org.apache.thrift.TEnum {
  UNLIMIT(0),
  DAY(1),
  HOUR(2);

  private final int value;

  private TEliteMessageFrequenceType(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static TEliteMessageFrequenceType findByValue(int value) { 
    switch (value) {
      case 0:
        return UNLIMIT;
      case 1:
        return DAY;
      case 2:
        return HOUR;
      default:
        return null;
    }
  }
}
