/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.sohu.bp.elite.model;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class TExpertTeamListResult implements org.apache.thrift.TBase<TExpertTeamListResult, TExpertTeamListResult._Fields>, java.io.Serializable, Cloneable {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("TExpertTeamListResult");

  private static final org.apache.thrift.protocol.TField EXPERT_TEAM_FIELD_DESC = new org.apache.thrift.protocol.TField("expertTeam", org.apache.thrift.protocol.TType.LIST, (short)1);
  private static final org.apache.thrift.protocol.TField TOTAL_FIELD_DESC = new org.apache.thrift.protocol.TField("total", org.apache.thrift.protocol.TType.I64, (short)2);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new TExpertTeamListResultStandardSchemeFactory());
    schemes.put(TupleScheme.class, new TExpertTeamListResultTupleSchemeFactory());
  }

  public List<TEliteExpertTeam> expertTeam; // required
  public long total; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    EXPERT_TEAM((short)1, "expertTeam"),
    TOTAL((short)2, "total");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // EXPERT_TEAM
          return EXPERT_TEAM;
        case 2: // TOTAL
          return TOTAL;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __TOTAL_ISSET_ID = 0;
  private byte __isset_bitfield = 0;
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.EXPERT_TEAM, new org.apache.thrift.meta_data.FieldMetaData("expertTeam", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, TEliteExpertTeam.class))));
    tmpMap.put(_Fields.TOTAL, new org.apache.thrift.meta_data.FieldMetaData("total", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(TExpertTeamListResult.class, metaDataMap);
  }

  public TExpertTeamListResult() {
    this.total = 0L;

  }

  public TExpertTeamListResult(
    List<TEliteExpertTeam> expertTeam,
    long total)
  {
    this();
    this.expertTeam = expertTeam;
    this.total = total;
    setTotalIsSet(true);
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public TExpertTeamListResult(TExpertTeamListResult other) {
    __isset_bitfield = other.__isset_bitfield;
    if (other.isSetExpertTeam()) {
      List<TEliteExpertTeam> __this__expertTeam = new ArrayList<TEliteExpertTeam>();
      for (TEliteExpertTeam other_element : other.expertTeam) {
        __this__expertTeam.add(new TEliteExpertTeam(other_element));
      }
      this.expertTeam = __this__expertTeam;
    }
    this.total = other.total;
  }

  public TExpertTeamListResult deepCopy() {
    return new TExpertTeamListResult(this);
  }

  @Override
  public void clear() {
    this.expertTeam = null;
    this.total = 0L;

  }

  public int getExpertTeamSize() {
    return (this.expertTeam == null) ? 0 : this.expertTeam.size();
  }

  public java.util.Iterator<TEliteExpertTeam> getExpertTeamIterator() {
    return (this.expertTeam == null) ? null : this.expertTeam.iterator();
  }

  public void addToExpertTeam(TEliteExpertTeam elem) {
    if (this.expertTeam == null) {
      this.expertTeam = new ArrayList<TEliteExpertTeam>();
    }
    this.expertTeam.add(elem);
  }

  public List<TEliteExpertTeam> getExpertTeam() {
    return this.expertTeam;
  }

  public TExpertTeamListResult setExpertTeam(List<TEliteExpertTeam> expertTeam) {
    this.expertTeam = expertTeam;
    return this;
  }

  public void unsetExpertTeam() {
    this.expertTeam = null;
  }

  /** Returns true if field expertTeam is set (has been assigned a value) and false otherwise */
  public boolean isSetExpertTeam() {
    return this.expertTeam != null;
  }

  public void setExpertTeamIsSet(boolean value) {
    if (!value) {
      this.expertTeam = null;
    }
  }

  public long getTotal() {
    return this.total;
  }

  public TExpertTeamListResult setTotal(long total) {
    this.total = total;
    setTotalIsSet(true);
    return this;
  }

  public void unsetTotal() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __TOTAL_ISSET_ID);
  }

  /** Returns true if field total is set (has been assigned a value) and false otherwise */
  public boolean isSetTotal() {
    return EncodingUtils.testBit(__isset_bitfield, __TOTAL_ISSET_ID);
  }

  public void setTotalIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __TOTAL_ISSET_ID, value);
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case EXPERT_TEAM:
      if (value == null) {
        unsetExpertTeam();
      } else {
        setExpertTeam((List<TEliteExpertTeam>)value);
      }
      break;

    case TOTAL:
      if (value == null) {
        unsetTotal();
      } else {
        setTotal((Long)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case EXPERT_TEAM:
      return getExpertTeam();

    case TOTAL:
      return Long.valueOf(getTotal());

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case EXPERT_TEAM:
      return isSetExpertTeam();
    case TOTAL:
      return isSetTotal();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof TExpertTeamListResult)
      return this.equals((TExpertTeamListResult)that);
    return false;
  }

  public boolean equals(TExpertTeamListResult that) {
    if (that == null)
      return false;

    boolean this_present_expertTeam = true && this.isSetExpertTeam();
    boolean that_present_expertTeam = true && that.isSetExpertTeam();
    if (this_present_expertTeam || that_present_expertTeam) {
      if (!(this_present_expertTeam && that_present_expertTeam))
        return false;
      if (!this.expertTeam.equals(that.expertTeam))
        return false;
    }

    boolean this_present_total = true;
    boolean that_present_total = true;
    if (this_present_total || that_present_total) {
      if (!(this_present_total && that_present_total))
        return false;
      if (this.total != that.total)
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  public int compareTo(TExpertTeamListResult other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;
    TExpertTeamListResult typedOther = (TExpertTeamListResult)other;

    lastComparison = Boolean.valueOf(isSetExpertTeam()).compareTo(typedOther.isSetExpertTeam());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetExpertTeam()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.expertTeam, typedOther.expertTeam);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetTotal()).compareTo(typedOther.isSetTotal());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetTotal()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.total, typedOther.total);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("TExpertTeamListResult(");
    boolean first = true;

    sb.append("expertTeam:");
    if (this.expertTeam == null) {
      sb.append("null");
    } else {
      sb.append(this.expertTeam);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("total:");
    sb.append(this.total);
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class TExpertTeamListResultStandardSchemeFactory implements SchemeFactory {
    public TExpertTeamListResultStandardScheme getScheme() {
      return new TExpertTeamListResultStandardScheme();
    }
  }

  private static class TExpertTeamListResultStandardScheme extends StandardScheme<TExpertTeamListResult> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, TExpertTeamListResult struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // EXPERT_TEAM
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list116 = iprot.readListBegin();
                struct.expertTeam = new ArrayList<TEliteExpertTeam>(_list116.size);
                for (int _i117 = 0; _i117 < _list116.size; ++_i117)
                {
                  TEliteExpertTeam _elem118; // required
                  _elem118 = new TEliteExpertTeam();
                  _elem118.read(iprot);
                  struct.expertTeam.add(_elem118);
                }
                iprot.readListEnd();
              }
              struct.setExpertTeamIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // TOTAL
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.total = iprot.readI64();
              struct.setTotalIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, TExpertTeamListResult struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.expertTeam != null) {
        oprot.writeFieldBegin(EXPERT_TEAM_FIELD_DESC);
        {
          oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, struct.expertTeam.size()));
          for (TEliteExpertTeam _iter119 : struct.expertTeam)
          {
            _iter119.write(oprot);
          }
          oprot.writeListEnd();
        }
        oprot.writeFieldEnd();
      }
      oprot.writeFieldBegin(TOTAL_FIELD_DESC);
      oprot.writeI64(struct.total);
      oprot.writeFieldEnd();
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class TExpertTeamListResultTupleSchemeFactory implements SchemeFactory {
    public TExpertTeamListResultTupleScheme getScheme() {
      return new TExpertTeamListResultTupleScheme();
    }
  }

  private static class TExpertTeamListResultTupleScheme extends TupleScheme<TExpertTeamListResult> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, TExpertTeamListResult struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetExpertTeam()) {
        optionals.set(0);
      }
      if (struct.isSetTotal()) {
        optionals.set(1);
      }
      oprot.writeBitSet(optionals, 2);
      if (struct.isSetExpertTeam()) {
        {
          oprot.writeI32(struct.expertTeam.size());
          for (TEliteExpertTeam _iter120 : struct.expertTeam)
          {
            _iter120.write(oprot);
          }
        }
      }
      if (struct.isSetTotal()) {
        oprot.writeI64(struct.total);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, TExpertTeamListResult struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(2);
      if (incoming.get(0)) {
        {
          org.apache.thrift.protocol.TList _list121 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, iprot.readI32());
          struct.expertTeam = new ArrayList<TEliteExpertTeam>(_list121.size);
          for (int _i122 = 0; _i122 < _list121.size; ++_i122)
          {
            TEliteExpertTeam _elem123; // required
            _elem123 = new TEliteExpertTeam();
            _elem123.read(iprot);
            struct.expertTeam.add(_elem123);
          }
        }
        struct.setExpertTeamIsSet(true);
      }
      if (incoming.get(1)) {
        struct.total = iprot.readI64();
        struct.setTotalIsSet(true);
      }
    }
  }

}

